Dataset:
  shape: [3900, 3072] # wxh
  keep_size_ratio: True
  img_url: /home/tmp/clpla/data/InprintSegmentation/train/images/
  mask_url: /home/tmp/clpla/data/InprintSegmentation/train/gt/
  recursive_loading: True

Test:
  img_url: /home/tmp/clpla/data/InprintSegmentation/test

Manager:
  experiment: Inprint_Segmentation
  run: Unet
  save_point: /usagers/clpla/Projects/runs
  gpu: [0,1]
  max_saved_model: 1
  num_workers: 8 # Workers used for parallel data loading
  dist_backend: nccl
  seed: 1234
  tracking_uri: http://localhost:5010
  artifact_uri: sftp://clement@m3202-10.demdgi.polymtl.ca/home/clement/Documents/Clement/runs/server/artifact
  grad_scaling: False
  amp: False

Preprocessing:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  random_crop: True
  crop_size: [512, 512]

Validation:
  size: 3
  log_interval: 50

Training:
  epochs: 350
  batch_size: 8
  ignore_index: -100

Loss:
  type: Dice
  fusion: mean
  params_loss:
    Dice:
      eps: 1
      mode: multiclass
      smooth: 0.5

Optimizer:
  solver: Adam
  params_solver:
    lr: 0.001
    weight_decay: 0.00001

Learning_rate_scheduler:
  update_type: on_epoch
  scheduler: CosineAnnealingLR
  params_scheduler:
    eta_min: 0.00001
    T_max: 350
    verbose: False

Network:
  architecture: Unet
  n_classes: 3
  synchronized_batch_norm: True
  pretrained: True
